# HTTP Server.
[server]
	Address        = ":8199"
	ServerRoot     = "public"
	ServerAgent    = "gf-demos"
	LogPath        = "/tmp/log/gf-demos/server"
	NameToUriType  = 2
	RouteOverWrite = true

# Logger configurations.
[logger]
    Path   = "/tmp/log/gf-demos"
    Level  = "all"
    Stdout = true

# Template view configurations.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database configurations.
[database]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/gf-demos/sql"
        Level  = "all"
        Stdout = true

# HTTP basic authentication passport/password for swagger api page.
[swagger]
    user = "123"
    pass = "123"
